Прикрепляю код для первого задания
gkanonimus/DBMS_task0 pull request #2
Opened 2022-10-10 12:55 UTC by gkanonimus

Вариант 3, среднее значение в массиве из элементов типа char
1.	Пользователь вводит размер одномерного массива size.
2.	Происходит создание одномерного массива values элементов типа char размерности size, заполненного псевдослучайными значениями.
3.	Вывод созданного массива на экран.
4.	Выполнение алгоритма algo над созданным массивом.
5.	Вывод результата применения алгоритма на экран.

2022-10-10 14:47 UTC, MarinaPaley requested changes

2022-10-10 14:47 UTC, MarinaPaley commented on progfinale.txt
> +void removearray(unsigned char* values);
`void removearray(unsigned char*& values)`

2022-10-10 14:47 UTC, MarinaPaley commented on progfinale.txt
> +
`const auto visual = 15;`

2022-10-10 14:47 UTC, MarinaPaley commented on progfinale.txt
> +        cout << (size_t)values[i] << " ";
Преобразование типа в С-стиле, нужно `static_cast<>()`

2022-10-10 14:47 UTC, MarinaPaley commented on progfinale.txt
> +size_t getsize();
Используйте `snake_case`

2022-10-30 19:06 UTC, gkanonimus commented
Добрый вечер, Марина Алексеевна! Исправил ошибки, прикрепил новый файл с верным разрешением

2022-10-31 13:39 UTC, MarinaPaley commented on progfinale.txt
>      if (values == nullptr) cout << "The array already removed\n";
нет `cout`

2022-10-31 13:42 UTC, MarinaPaley requested changes

2022-10-31 13:42 UTC, MarinaPaley commented on finale_prog.cpp
> +    }
в отдельную функцию

2022-10-31 13:42 UTC, MarinaPaley commented on finale_prog.cpp
> +size_t algo(unsigned char* values, const size_t size) {
Согласно [`SOLID Principal`](https://ru.wikipedia.org/wiki/SOLID_(%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BD%D0%BE-%D0%BE%D1%80%D0%B8%D0%B5%D0%BD%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)), каждый класс / функция / метод должен иметь только одну ответственность

2022-10-31 13:42 UTC, MarinaPaley commented on finale_prog.cpp
> +    delete[] values;
Массив необходимо удалять следующим безопасным способом
```cpp
if (array != nullptr)
{
   delete[] array;
   array = nullptr;
}
```

2022-11-07 12:29 UTC, gkanonimus commented
Исправил ошибки, прошу проверить еще раз

2022-11-07 13:07 UTC, MarinaPaley approved these changes

2022-11-07 13:09 UTC, merged